/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Projectsemester2;

import java.awt.HeadlessException;
import java.io.InputStream;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import projectsemester2.Config;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Sandi RF
 */
public class Data_transaksi extends javax.swing.JFrame {
    Config k;
    /**
     * Creates new form Data_transaksi
     */
    private String nama, harga, stok, id;

    public Data_transaksi() {
        initComponents();
        setLocationRelativeTo(this);
        tabletrans();
    }

    public void tanggal() {
        DateFormat tgl = new SimpleDateFormat("dd-MM-yyyy");
        String tanggal = tgl.format(Calendar.getInstance().getTime());
        jTextField4.setText(tanggal);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabletrans = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        namabar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jml_beli = new javax.swing.JTextField();
        jmlbayar = new javax.swing.JTextField();
        simpan = new javax.swing.JButton();
        idbar = new javax.swing.JTextField();
        struk = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        bayar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        hapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(742, 549));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setText("Data Transaksi ");

        back.setBackground(new java.awt.Color(204, 204, 204));
        back.setText("<- Back");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectsemester2/1b.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 682, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(448, 448, 448)
                .addComponent(jLabel4)
                .addGap(43, 43, 43))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 10, 1700, 107);

        tabletrans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabletrans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabletransMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabletrans);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(60, 530, 1550, 310);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Id Barang");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(520, 180, 124, 24);

        namabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namabarActionPerformed(evt);
            }
        });
        namabar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                namabarKeyTyped(evt);
            }
        });
        jPanel1.add(namabar);
        namabar.setBounds(770, 130, 260, 30);

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tanggal Transaksi");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(520, 240, 170, 24);

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Jumlah Beli");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(520, 300, 140, 24);

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nama Barang");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(520, 130, 124, 24);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(770, 240, 260, 30);

        jml_beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jml_beliActionPerformed(evt);
            }
        });
        jml_beli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jml_beliKeyTyped(evt);
            }
        });
        jPanel1.add(jml_beli);
        jml_beli.setBounds(770, 300, 260, 30);

        jmlbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlbayarActionPerformed(evt);
            }
        });
        jPanel1.add(jmlbayar);
        jmlbayar.setBounds(1330, 470, 190, 30);

        simpan.setBackground(new java.awt.Color(0, 255, 0));
        simpan.setFont(new java.awt.Font("Georgia", 1, 13)); // NOI18N
        simpan.setText("Simpan");
        simpan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        jPanel1.add(simpan);
        simpan.setBounds(770, 350, 260, 30);

        idbar.setText("barang tidak ditemukan");
        idbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idbarActionPerformed(evt);
            }
        });
        idbar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idbarKeyTyped(evt);
            }
        });
        jPanel1.add(idbar);
        idbar.setBounds(770, 180, 260, 30);

        struk.setBackground(new java.awt.Color(0, 204, 204));
        struk.setFont(new java.awt.Font("Georgia", 1, 13)); // NOI18N
        struk.setText("Struk");
        struk.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        struk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strukActionPerformed(evt);
            }
        });
        jPanel1.add(struk);
        struk.setBounds(1023, 430, 90, 30);

        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(1040, 240, 30, 25);

        bayar.setBackground(new java.awt.Color(255, 51, 51));
        bayar.setFont(new java.awt.Font("Georgia", 1, 13)); // NOI18N
        bayar.setText("Bayar");
        bayar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bayar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bayarMouseClicked(evt);
            }
        });
        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });
        jPanel1.add(bayar);
        bayar.setBounds(1130, 430, 110, 30);

        jLabel3.setBackground(new java.awt.Color(255, 51, 51));
        jLabel3.setFont(new java.awt.Font("Georgia", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Total bayar");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(1330, 450, 100, 15);

        hapus.setBackground(new java.awt.Color(255, 51, 51));
        hapus.setFont(new java.awt.Font("Georgia", 1, 13)); // NOI18N
        hapus.setText("Hapus");
        hapus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel1.add(hapus);
        hapus.setBounds(927, 430, 80, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -10, 1680, 880);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jml_beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jml_beliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jml_beliActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new utama().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void namabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namabarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namabarActionPerformed

    private void idbarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idbarKeyTyped
        // TODO add your handling code here:
        try {
            String query = "select * from barang where nama_barang='" + namabar.getText() + "'";
            java.sql.Connection con = (Connection) Config.getKoneksi();
            java.sql.PreparedStatement pst = con.prepareStatement(query);
            java.sql.ResultSet data = pst.executeQuery();
            while (data.next()) {
                id = data.getString(1);
            }
        } catch (Exception e) {

        }
        idbar.setText(id);
    }//GEN-LAST:event_idbarKeyTyped

    private void namabarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namabarKeyTyped
        // TODO add your handling code here:
        try {
            String query = "select * from barang where nama_barang='" + namabar.getText() + "'";
            java.sql.Connection con = (Connection) Config.getKoneksi();
            java.sql.PreparedStatement pst = con.prepareStatement(query);
            java.sql.ResultSet data = pst.executeQuery();
            while (data.next()) {
                id = data.getString(2);
                harga = data.getString(4);
            }
        } catch (Exception e) {

        }
        idbar.setText(id);
    }//GEN-LAST:event_namabarKeyTyped

    private void jml_beliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jml_beliKeyTyped
        // TODO add your handling code here:
        int harga_awal = Integer.parseInt(harga);
        String barang = jml_beli.getText() + evt.getKeyChar();
        int jmlbarang = Integer.parseInt(barang);
        int hargatotal = harga_awal * jmlbarang;
        String nilai = Integer.toString(hargatotal);
        jmlbayar.setText(nilai);
    }//GEN-LAST:event_jml_beliKeyTyped

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        tanggal();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        try {

            String tes = "INSERT INTO transaksi(nama_barang,id_barang,Tanggal_trans,jum_beli,jum_bayar)  VALUES('" + namabar.getText() + "','" + idbar.getText() + "','" + jTextField4.getText() + "','" + jml_beli.getText() + "','" + jmlbayar.getText() + "')";
            java.sql.Connection conn = (Connection) Config.getKoneksi();
            java.sql.PreparedStatement pstm = conn.prepareStatement(tes);
            pstm.execute();
            tabletrans();

        } catch (SQLException e) {
            System.out.println("error" + e.getMessage());
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void tabletransMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabletransMouseClicked
        // TODO add your handling code here:
        namabar.setText(tabletrans.getValueAt(tabletrans.getSelectedRow(),2)+"");
        idbar.setText(tabletrans.getValueAt(tabletrans.getSelectedRow(),1)+"");
        jTextField4.setText(tabletrans.getValueAt(tabletrans.getSelectedRow(),3)+"");
        jml_beli.setText(tabletrans.getValueAt(tabletrans.getSelectedRow(),4)+"");
        jmlbayar.setText(tabletrans.getValueAt(tabletrans.getSelectedRow(),5)+"");
    }//GEN-LAST:event_tabletransMouseClicked

    private void idbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idbarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idbarActionPerformed

    private void strukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strukActionPerformed
        // TODO add your handling code here:
        try {
            InputStream is = Data_transaksi.class.getResourceAsStream("/projectsemester2/struk.jasper");
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost:3306/mini_market", "root", "");
            JasperPrint jsPrint = JasperFillManager.fillReport(is, null, koneksi);
            JasperViewer.viewReport(jsPrint, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "gagal mencetak laporan karena :"
                    + e.getMessage(), "cetak laporan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_strukActionPerformed

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed
        // TODO add your handling code here:

        String uang = null;
        try {
            String query = "select SUM(jum_bayar) FROM transaksi";
            java.sql.Connection con = (Connection) Config.getKoneksi();
            java.sql.PreparedStatement pst = con.prepareStatement(query);
            java.sql.ResultSet data = pst.executeQuery();
            while (data.next()) {
                uang = data.getString(1);
                int bayar = Integer.parseInt(uang);
                int uangpembeli = Integer.parseInt(JOptionPane.showInputDialog("uang yang harus di bayar " + bayar + "\nmasukan uang anda"));
                int kembalian = uangpembeli - bayar;
                JOptionPane.showConfirmDialog(null, "kembalian anda " + kembalian);

                //cara masukan bilangan kembaalian dah hasil total nya 
                try {

                    String tes = "INSERT INTO transaksi(nama_barang,id_barang,Tanggal_trans,jum_beli,jum_bayar)  VALUES('?','?','?','kembalian  "+kembalian+"','total  "+bayar+"')";
                    java.sql.Connection conn = (Connection) Config.getKoneksi();
                    java.sql.PreparedStatement pstm = conn.prepareStatement(tes);
                    pstm.execute();
                    tabletrans();

                } catch (SQLException e) {
                    System.out.println("error" + e.getMessage());
                }

            }
        } catch (Exception e) {
            System.out.println("error" + e.getMessage());
        }
    }//GEN-LAST:event_bayarActionPerformed

    private void bayarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bayarMouseClicked
        // TODO add your handling code here:
        new Data_barang().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bayarMouseClicked

    private void jmlbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlbayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlbayarActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        try{
        String sql ="DELETE FROM transaksi WHERE nama_barang ='"+namabar.getText()+"'";
            java.sql.Connection conn=(Connection)Config.getKoneksi();
            java.sql.PreparedStatement pstm=conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Data berhasil di Hapus");
        }catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        DefaultTableModel model = (DefaultTableModel)tabletrans.getModel();
        model.setRowCount(0);
        tabletrans();
    }//GEN-LAST:event_hapusActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_backMouseClicked

    private void tabletrans() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("nomor");
        model.addColumn("id barang");
        model.addColumn("nama barang");
        model.addColumn("tanggal transaksi");
        model.addColumn("jumlah beli");
        model.addColumn("jumlah bayar");

        try {
            String udin = "SELECT * FROM transaksi";
            java.sql.Connection con = (Connection) Config.getKoneksi();
            java.sql.PreparedStatement pst = con.prepareStatement(udin);
            java.sql.ResultSet data = pst.executeQuery();
            while (data.next()) {
                model.addRow(new Object[]{
                    data.getString(1),
                    data.getString(2),
                    data.getString(3),
                    data.getString(4),
                    data.getString(5),
                    data.getString(6)
                });
            }

        } catch (Exception e) {
            System.out.println("error" + e.getMessage());
        }

        tabletrans.setModel(model);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data_transaksi.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data_transaksi.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data_transaksi.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data_transaksi.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data_transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton bayar;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField idbar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jml_beli;
    private javax.swing.JTextField jmlbayar;
    private javax.swing.JTextField namabar;
    private javax.swing.JButton simpan;
    private javax.swing.JButton struk;
    private javax.swing.JTable tabletrans;
    // End of variables declaration//GEN-END:variables
}
